### ISSUE TITLE
input ondisc files

### ISSUE THREAD

**Issue by lo2811** [timothy-barry/sceptre-pipeline-1#3]
Hello,

First, thank you for the great tool for multiplexing CRISPRi screen. I would want to use sceptre for my dataset of multiplex gRNA (10-15gRNA/cells) for a pool of 1000 gRNA. I was able to follow your tutorial for small dataset, but am stuck now for the large scale. 
Can you please provide more instructions how to generate the required input files using ondisc? 
Thank you,
Linh

**Comment by timothy-barry** [comment]
Hi Linh,

Thank you for reaching out. I will get back to you with some documentation within the next day or so.

Thanks,
Tim

**Comment by timothy-barry** [comment]
This issue has been resolved over email. Closing.
